### ISSUE TITLE
Update to latest ignition libraries

### ISSUE THREAD

**Issue by hidmic** [maliput/maliput_infrastructure#103]
## Description

Delphyne* packages rely on ignition libraries' versions that are not the latest ones and in some cases simply old. This prevents many upstream fixes to reach us. It'd be ideal to bump the versions we rely on. 

## Tasks

- [ ] Assess the impact of switching to latest ignition libraries.
- [ ] Adapt `delphyne` codebases to use latest ignition libraries.
- [ ] Update .repos files and prerequisites to make use of the new versions.
