### ISSUE TITLE
Workspace opensourcing

### ISSUE THREAD

**Issue by agalbachicar** [maliput/maliput_infrastructure#135]
List of tasks that would allow the workspace to be public

- [ ] Solidify build scripts, identify supported platforms
- [ ] Review installation documentation #139 
- [x] Other documentation links #229 
- [ ] Limited CI builds on public facing repo? #136 
- [ ] Quality of life improvements
- [ ] General Roadmap of the next 6th months of development
- [ ] We'd need a logo :-), trademark, legal protections 
- [x] Licenses
- [ ] Patenting
- [ ] Contributions
- [ ] Questions and requests
- [ ] Demos

**Comment by tfoote** [comment]
Preparing release repositories: https://github.com/ros2-gbp/ros2-gbp-github-org/pull/68

I have skipped infrastructure, drake, and delphyne ones for the first cycle.
