### ISSUE TITLE
[META] Use cmake as any other programming language

### ISSUE THREAD

**Issue by agalbachicar** [maliput/maliput_infrastructure#146]
- [x] Be as much compatible as possible with ament
- [x] Define minimum version of cmake in all packages
- [x] Use namespacing in targets, library file names
- [x] Use underscores everywhere instead of hyphens
- [x] Header files that should be exported must in inside `include/package_name` folder at the root of the package.
- [x] Decide what to do with SSE flags, host OS etc to keep and which to remove.
- [x] Use shared libraries everywhere.
- [x] Export targets everywhere (except those that don't need to)
- [x] Standardize installation paths.
- [x] Document cmake usage using ROS REP as much as possible then the other things that we decide here.
