### ISSUE TITLE
Generate great documentation

### ISSUE THREAD

**Issue by agalbachicar** [maliput/maliput_infrastructure#229]
Part of #135 

Should document into maliput_documentation (logging here because it affects repositories out of the scope of maliput repos now):

- [x] Make doxygen documentation errors to be failures #227
- [x] Define whether to include delphyne repos into doxygen documentation. If yes, do it! https://github.com/ToyotaResearchInstitute/maliput_infrastructure/issues/229#issuecomment-913712159
- [x] Python documentation (of bindings, demos, delphyne, etc.) https://github.com/ToyotaResearchInstitute/maliput_py/pull/19
- [x] maliput_integration applications https://github.com/ToyotaResearchInstitute/maliput_infrastructure/issues/229#issuecomment-915356528
- [x] maliput_malidrive xodr tools. https://github.com/ToyotaResearchInstitute/maliput_malidrive/pull/170
- [x] maliput_malidrive forensics ->https://docs.google.com/document/d/1R1GYt0QkzUOdnyZxz2QhOh1tq6s7iLIu07Gc_REqTj0/edit#heading=h.5h8y2rlp1xds
- [x] delphyne_demos
- [x] maliput visualizer
- [x] maliput plugin architecture https://github.com/ToyotaResearchInstitute/maliput/pull/441
