### ISSUE TITLE
[META] CI: Refactor CI workflows to rely on ros-action-ci instead

### ISSUE THREAD

**Issue by francocipollone** [maliput/maliput_infrastructure#268]
Affects all the repositories
### Summary
As repositories are public we can start relying on `ros-action-ci` actions

Some clean up to have in mind:
- [ ] https://github.com/maliput/maliput_infrastructure/issues/260 https://github.com/maliput/maliput_infrastructure/pull/266
- [ ] https://github.com/maliput/maliput_infrastructure/issues/263
- [ ] https://github.com/maliput/maliput_infrastructure/issues/261

### Victory condition 

Use ros-action-ci for:
 - [ ] rosdep install, build and test the repository
   - repos file could be provided for checking out the dependency repos.
   - Multi-repos development supported (aka interdependent pull requests). See [here](https://github.com/ros-tooling/action-ros-ci#interdependent-pull-requests-or-merge-requests)
   - we need skip-keys because of pybind11, missing feature 
     - [ ] Contribuite with new feature to ros-action-ci https://github.com/ros-tooling/action-ros-ci/pull/753 
 - [ ] Run sanitizers 
   - We should look into colocon mixers
      - https://github.com/colcon/colcon-mixin-repository/
      - https://colcon.readthedocs.io/en/released/reference/mixin-arguments.html   
 - [ ] Run Scan build

**Comment by francocipollone** [comment]
CC: @agalbachicar

**Comment by francocipollone** [comment]
My only concern goes with `drake_vendor`: With [`drake_vendor`](https://github.com/ToyotaResearchInstitute/drake_vendor#basic-usage---downstream-cmake-packages) we have to execute an script for installing it in the system. I guess that installing drake before running the `ros-action-ci` action should be enough

**Comment by francocipollone** [comment]
### More info

We currently have 3 workflows in the repositories.

 - build.yaml: Simple GCC build and test. It builds without docs first and then with docs (-DBUILD_DOCS cmake args)
   - without docs: **Using ros-action-ci is straight forward**
   - with docs: After changing the `ament_cmake_doxygen` dependency to be <doc_depend> to be compatible with `Ros build farm`, the dependency is missed when build up-to maliput, therefore `ament_cmake_doxygen` doesn't get built. So, **Using ros-action-ci here isn't straight forward**. This should be ok when [migrating to use `rosdocs2`](https://github.com/maliput/maliput_infrastructure/issues/265) instead
   
 - sanitizers.yaml: `clang` build + `asan` + `ubsan` + `tsan` sanitizers.
   - GCC is expected to be used when using `ros-action-ci`. Is `clang` still needed to be supported?
   - `asan` (gcc) is supported by ros-action-ci
   - `tsan` and `ubsan` might be addressed via colcon mixers. PoC needed. 
   
 - scan_build.yaml: Runs `scan-build` using `clang`
 
 **How this complies with long term ROS build farm?**
 - In the build farm, CI is expected to be run(gcc+build+tests) for pull requests targeting main,
   - Having a GH Action CI using ros-action-ci for push and pull requests is still valid. 
 - Sanitizers might be possible to be run in ROS build farm, but only for `gcc` compiler. 
   - If `clang` support is still needed, we will still rely on gh actions for this.
 - Scan build 
   - If `clang` support is still needed, we will still rely on gh actions for this.

**Comment by francocipollone** [comment]
### Steps

- [ ] Use ros-action-ci for `build.yml` workflow accross the repositories.
- [ ] Migrate sanitizer and scan build workflows to `maliput_bazel` repository.
- [ ] Use ros-action-ci to enable gcc-santizers in a new workflow.

Note: https://github.com/maliput/maliput_infrastructure/issues/273 will cause not to be able to test the documentation as `ament_cmake_doxygen` doesn't get build as `colcon` doesn't finds `ament_cmake_doxygent` a dependency when `<doc_depend>` labels is used for it.
