### ISSUE TITLE
Prepare for Foxy EOL

### ISSUE THREAD

**Issue by francocipollone** [maliput/maliput_infrastructure#298]
### Summary

ROS Foxy version EOL is during May.

There are some tasks should be done within this time frame:
 - Before hitting the freeze we should release all the packages to the last state.
 - Changes in CI due to EOL distros

### Tasks

 - [ ] Release new maliput-ros packages:
      - maliput_ros, maliput_ros_interfaces, maliput_ros_translations
        - [x] Request release repositories at https://github.com/ros2-gbp/ros2-gbp-github-org
        - [ ] Release them
 - [x] Release packages with changes that weren't synced:
     - [x] maliput_dragway
     - [x] maliput_drake
     - [x] maliput_multilane
     - [x] maliput_osm
     - [x] maliput_integration
 - [ ] CI: `rosdep install` commands will require `--include-eol-distros` argument. To be propagated to all the repos.
