### ISSUE TITLE
Support Ubuntu Jammy / ROS Humble

### ISSUE THREAD

**Issue by francocipollone** [maliput/maliput_infrastructure#299]
## Context

As foxy reached the end of life, humble is the following LTS version of ROS.

## General tasks
- [ ] Provide docker workspace for humble development
- [ ] Add/Update CI to target humble/jammy as well.
- [ ] Set up documentation/readthedocs for humble branch  

## Tasks per package

- [ ] Create `humble` branches.
- [ ] Adapt package to support humble/jammy
      - API changes of dependencies/deprecations/etc
- [ ] Package CI
- [ ] Modify necessary documentation

## Identified issues so far on humble:
 - [ ] maliput_py: 
      -  pybind11's changes on cmake macros need to be fixed. 
 - [ ] maliput_viz:
      - Scene3d plugin is still being used on ign-gui6, however traffic lights aren't being rendered anymore.
 - [ ] Gtest: Some undefined reference to `testing::internal::PrintBytesInObjectTo  happens when compiling tests.
