### ISSUE TITLE
[META] Maliput PyPI Distribution

### ISSUE THREAD

**Issue by francocipollone** [maliput/maliput_infrastructure#304]
### Objective

 - Distribute Maliput over the Python Package Index repository. 
 
 ### Proof of concept:
 -  maliput_py
[cmake_wheel branch](https://github.com/maliput/maliput_py/tree/francocipollone/cmake_wheel)
 - maliput_malidrive
[cmake_wheel branch](https://github.com/maliput/maliput_malidrive/tree/francocipollone/cmake_wheel)
 
 ### Tasks:
 - [ ] Create user/organization in [test_pypi](https://test.pypi.org/)
 - [ ] Extend https://github.com/Klebert-Engineering/python-cmake-wheel to be able to indicate `entry_point`
      - For the PoC it was used [this branch with hardcoded values](https://github.com/Klebert-Engineering/python-cmake-wheel/compare/main...francocipollone:python-cmake-wheel:francocipollone/add_entry_point)
 - [ ] maliput-maliput_py - Automatize creation of wheel 
     - Polish PoC: [cmake_wheel branch](https://github.com/maliput/maliput_py/tree/francocipollone/cmake_wheel) 
 - [ ] maliput_malidrive - Automatize creation of wheel
     - Polish PoC: [cmake_wheel branch](https://github.com/maliput/maliput_malidrive/tree/francocipollone/cmake_wheel)
 - [ ] Support for other backends:
    - [ ] Dragway
    - [ ] Multilane
    - [ ] Osm
  - [ ] Push to test-pypi 
  - [ ] Automatize (could be manually executed) uploading to test-pypi
