### ISSUE TITLE
Workspace Improvements Meta Issue

### ISSUE THREAD

**Issue by liangfok** [maliput/maliput_infrastructure#78]
This is a meta ticket tracking ways in which the workspace can be improved.

- [x] Enforce 1 Reviewer (including admins) process for master on all of our repositories (e.g. [maliput settings](https://github.com/ToyotaResearchInstitute/maliput/settings/branch_protection_rules/5464198)
- [ ] [Liang] Style guide re-introduced and documented (TRI Driving's guide as markdown in a `docs` dir)
- [x] Drop the redundant maliput directory (i.e. second one in `maliput/maliput/maliput/include/maliput`
- [ ] ~#72 - Need ability to abort exiting a workspace~
- [x] #68 - Workspace Creation Process Should Be Shortened
- [x] #66 - Prevent maliput_ws from being opened multiple times
- [ ] #35 - Instructions on how to update your workspace sources
- [x] #31 - Maliput and Malidrive should be pegged to specific SHAs, blocking on #35
